changed scp to rsync

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -21,32 +21,32 @@ jobs:
       run: |
         docker run -d --name quarto-container -v "$(pwd)":/project rocker/verse tail -f /dev/null
 
-        docker exec quarto-container apt update && \
-
-        docker exec quarto-container apt install -y texlive-fonts-recommended texlive-fonts-extra && \
-        docker exec quarto-container R -e "install.packages(c('kableExtra','scholar','bib2df','RCurl', 'europepmc'))"
-
-    # 3. Install tth
-    - name: Install tth
-      run: |
-        docker exec quarto-container sh -c "apt-get update && apt-get install -y tth"
-
-    # 4. Get the citation counts
-    #- name: Run R script to get citation counts
-    #  run: |
-    #    docker exec quarto-container sh -c "cd /project && Rscript rscripts/get_citation_counts.R"
-
-    # 5. Renew the existing citation_counts.rds file
-    - name: Commit and push changes if any
-      run: |
-        git config --global user.name "GitHub Actions"
-        git config --global user.email "github-actions@github.com"
-
-        git add citation_counts.rds
-
-        git commit -m "Automatic update of citation counts on $(date -I)" || echo "No changes to commit"
-
-        git push -o ci.skip https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Huber-group-EMBL/Huber-group-EMBL.github.io.git HEAD:automated_branch || echo "No changes to commit"
+#        docker exec quarto-container apt update && \
+#
+#        docker exec quarto-container apt install -y texlive-fonts-recommended texlive-fonts-extra && \
+#        docker exec quarto-container R -e "install.packages(c('kableExtra','scholar','bib2df','RCurl', 'europepmc'))"
+#
+#    # 3. Install tth
+#    - name: Install tth
+#      run: |
+#        docker exec quarto-container sh -c "apt-get update && apt-get install -y tth"
+#
+#    # 4. Get the citation counts
+#    #- name: Run R script to get citation counts
+#    #  run: |
+#    #    docker exec quarto-container sh -c "cd /project && Rscript rscripts/get_citation_counts.R"
+#
+#    # 5. Renew the existing citation_counts.rds file
+#    - name: Commit and push changes if any
+#      run: |
+#        git config --global user.name "GitHub Actions"
+#        git config --global user.email "github-actions@github.com"
+#
+#        git add citation_counts.rds
+#
+#        git commit -m "Automatic update of citation counts on $(date -I)" || echo "No changes to commit"
+#
+#        git push -o ci.skip https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Huber-group-EMBL/Huber-group-EMBL.github.io.git HEAD:automated_branch || echo "No changes to commit"
 
     # 5.5 Check if all pdfs are on /g/huber/www-huber/pub/pdf/
     - name: Sync pdfs to /g/huber/www-huber/pub/pdf/
@@ -55,65 +55,66 @@ jobs:
         docker exec quarto-container sh -c "mkdir .ssh && echo '${{ secrets.SSH_PRIVATE_KEY }}' > key.pem && chmod 600 key.pem"
         
         # Step 2: Add remote host to known_hosts
-        docker exec quarto-container sh -c "cd .ssh && ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts"
+        docker exec quarto-container sh -c "cd ./.ssh && ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts"
 
         # Step 3: Run scp
-        docker exec quarto-container sh -c "scp -i key.pem -r project/test/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/g/huber/www-huber/pub/pdf/"
+        docker exec quarto-container sh -c "rsync -avz -e 'ssh -i ./.ssh/key.pem -o StrictHostKeyChecking=no' project/test/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/g/huber/www-huber/pub/pdf/"
+        #docker exec quarto-container sh -c "scp -i key.pem -r project/test/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/g/huber/www-huber/pub/pdf/"
 
-    # 6. Prepare the citations
-    - name: Run R script to prepare the citations
-      run: |
-        docker exec quarto-container sh -c "cd /project && Rscript rscripts/prepare_citations.R"
-
-    # 6. Make BBL
-    - name: Make BBL
-      run: |
-        docker exec quarto-container sh -c "cd /project && Rscript rscripts/makebbl.R"
-
-    # 6. Create the page
-    - name: Run R script to create the page
-      run: |
-        # Ensure necessary dependencies exist
-        docker exec quarto-container sh -c "cd /project && tth index"
-
-        # Remove unnecessary files inside the container
-        docker exec quarto-container sh -c "cd /project && rm -f index.aux index.blg index.log index.out index.pdf lopcit.bib publ.rda index.bbl"
-
-        # Run the R script inside the container
-        docker exec quarto-container sh -c "cd /project && Rscript rscripts/prochtml.R"
-
-        # Remove the old index.html (if needed outside the container)
-        rm -f index.html
-
-    # 6. Render the Quarto project
-    - name: Render Quarto project
-      run: |
-        docker exec quarto-container R --version
-
-        docker exec quarto-container quarto render /project --cache-refresh
-
-        ls -l _site
-
-    # 7. Setup MinIO client
-    - name: Setup MinIO client
-      uses: lovellfelix/minio-deploy-action@v1
-
-      with:
-        endpoint: https://s3.embl.de/
-
-        access_key: 4kRFKz352s8UbsA6Pycq
-
-        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
-
-        bucket: 'www-huber'
-
-        target_dir: '/group/'
-
-        source_dir: '_site'
-
-    # 8. Clean up Docker container
-    - name: Clean up Docker container
-      run: |
-        docker stop quarto-container
-
-        docker rm quarto-container
+#    # 6. Prepare the citations
+#    - name: Run R script to prepare the citations
+#      run: |
+#        docker exec quarto-container sh -c "cd /project && Rscript rscripts/prepare_citations.R"
+#
+#    # 6. Make BBL
+#    - name: Make BBL
+#      run: |
+#        docker exec quarto-container sh -c "cd /project && Rscript rscripts/makebbl.R"
+#
+#    # 6. Create the page
+#    - name: Run R script to create the page
+#      run: |
+#        # Ensure necessary dependencies exist
+#        docker exec quarto-container sh -c "cd /project && tth index"
+#
+#        # Remove unnecessary files inside the container
+#        docker exec quarto-container sh -c "cd /project && rm -f index.aux index.blg index.log index.out index.pdf lopcit.bib publ.rda index.bbl"
+#
+#        # Run the R script inside the container
+#        docker exec quarto-container sh -c "cd /project && Rscript rscripts/prochtml.R"
+#
+#        # Remove the old index.html (if needed outside the container)
+#        rm -f index.html
+#
+#    # 6. Render the Quarto project
+#    - name: Render Quarto project
+#      run: |
+#        docker exec quarto-container R --version
+#
+#        docker exec quarto-container quarto render /project --cache-refresh
+#
+#        ls -l _site
+#
+#    # 7. Setup MinIO client
+#    - name: Setup MinIO client
+#      uses: lovellfelix/minio-deploy-action@v1
+#
+#      with:
+#        endpoint: https://s3.embl.de/
+#
+#        access_key: 4kRFKz352s8UbsA6Pycq
+#
+#        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
+#
+#        bucket: 'www-huber'
+#
+#        target_dir: '/group/'
+#
+#        source_dir: '_site'
+#
+#    # 8. Clean up Docker container
+#    - name: Clean up Docker container
+#      run: |
+#        docker stop quarto-container
+#
+#        docker rm quarto-container
